config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'

  get 'pages/home_page'
  get 'users/outlet_list'
  devise_for :users
  resource :batches, only: %i[update create]
  resources :companies
  devise_for :outlets, path: 'auth', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
  # devise_scope :outlet do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  # end

  resources :outlets do
    resources :products
  end

end

app/models/outlet.rb
# frozen_string_literal: true

class Outlet < ApplicationRecord
  has_one :user
  belongs_to :company
  has_many :products, dependent: :destroy
  has_many :batches

  enum outlet_category: ['Продуктовый магазин', 'Пекарня', 'Кофейня', 'Ресторан', 'Булочная']
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController

  before_action :set_outlet, only: %i[show edit update destroy]

  def show
    @batch = @outlet.batches.where(
      'DATE(activation_start) = ? AND activation_end > ?' , Date.current.to_s, Time.current
    ).first
    @products = @batch&.products
  end

  def new
    @outlet = Outlet.find(params[:id])
  end

  def edit
  end

  def create
    @outlet = Outlet.new(outlet_params)

    respond_to do |format|
      if @outlet.save
        format.html { redirect_to @outlet, notice: 'Outlet was successfully created.' }
        format.json { render :show, status: :created, location: @outlet }
      else
        format.html { render :new }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @outlet.update(outlet_params)
        format.html { redirect_to @outlet, notice: 'Outler was successfully updated.' }
        format.json { render :show, status: :ok, location: @outlet }
      else
        format.html { render :edit }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @outlet.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Outlet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_outlet
   @outlet = Outlet.find(params[:id])
  end

  def outlet_params
    params.require(:outlet).permit(
      :user_id,
      :outlet_category,
      :address,
      :company_id,
      :email,
      :password
    )
  end
end

app/helpers/outlets_helper.rb
module OutletsHelper
  def display_full_address(address)
    return '' if address.blank?


    "#{address['city']}, #{address['street']}, д. #{address['apartment']}, #{address['block']}"
  end

  def display_title_address(address)
    return '' if address.blank?

    "#{address['street']}"
  end
end

app/views/outlets/_form.html.slim
= form_with(model: outlet, local: true) do |form|
  - if outlet.errors.any?
    #error_explanation
      h2
        = pluralize(outlet.errors.count, "error")
        |  prohibited this outlet from being saved:
      ul
        - outlet.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :outlet_category
    = form.text_field :outlet_category
  .field
    = form.label :company_id
    = form.text_field :company_id
  .field
    = form.label :user_id
    = form.text_field :user_id
  .actions
    = form.submit

app/views/outlets/_outlet_card.html.slim
= link_to outlet do
  .outlet_card
    .cover
      = image_tag(outlet.company.company_cover.to_s)
    .outlet_card_info
      h3 #{outlet.company.company_name + ', ' + display_title_address(outlet.address)}
      .details
        p #{outlet.company.company_category}
        span •
        p.orange #{batch.products_count} предложений

app/views/outlets/new.html.slim
h1
  | New Outlet
= render 'form', outlet: @outlet
= link_to 'Back', outlets_path

app/views/outlets/show.html.slim
.outlet_container
  .outlet_banner
  .outlet_info
    h1  #{@outlet.company.company_name + ', ' + display_title_address(@outlet.address)}
    - if @batch
      h4
        span
        | акция до #{@batch.activation_end.strftime("%H:%M")}

  p.location #{display_full_address(@outlet.address)}

- if @products.present?
  .menubar
    hr.separator
    .items
      - Product.categories.each do |key, i|
        h4.menu_item onclick="checkClick(this, '#{i}')" #{key}

    hr.separator

  - Product.categories.each do |category_name, index|
    - products = @products.where(category: category_name)
    - next if products.blank?
    .batch
      .batch_block
        .batch_block_title
          h2[id = "category_#{index}"] = category_name
        .batch_block_cards
          - @products.each do |product|
            = render partial: 'products/product_card', locals: {product: product, discount: @batch.discount.to_i}

    hr.separator

  .banner

  .modal.hide.fade
    .modal-header
      button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
      h3.modal-heading Modal header
    .modal-body
      p One fine body…
    .modal-footer
      a.btn data-dismiss="modal" href="#"  Close
      a.btn.btn-primary href="#"  Add to Cart