config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'

  get 'pages/home_page'
  get 'users/outlet_list'
  devise_for :users
  resource :batches, only: %i[update create]
  resources :companies
  devise_for :outlets, path: 'auth', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
  # devise_scope :outlet do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  # end

  resources :outlets do
    resources :products
  end

end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_one :user
  has_many :outlets
  accepts_nested_attributes_for :user
  mount_uploader :company_cover, CompanyCoverUploader

  enum company_category: ['Продуктовый магазин', 'Пекарня', 'Кофейня', 'Ресторан', 'Булочная']
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController

  before_action :set_company, only: %i[show edit update destroy]

  def index
    @companies = Company.all
  end

  def show
    # @companies_batch = Company.all
    # @outlets = @company.outlets
    @outlets = @company.outlets
  end

  def new
    @company = Company.new
    @company.build_user
  end

  def edit; end

  def create
    @company = Company.new(company_params)
    # @company.user = current_user
    # current_user.company = @company

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }

        User.find(@company.user_id).update(company_id: @company.id)
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:company_name, :company_category, :user_id, user_attributes: [:email, :password, :company_id])
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
  def company_categories
    Company.company_categories.collect do |k, v|
      k
    end
  end
end

app/views/companies/_company_card.html.slim
//= link_to item_path(item_card) do
.company_card
  .cover
  .item_card_info
    h3 Хлеб Насущный на какой-то там длинной улице
    .details
      p Здоровая еда
      span •
      p.orange 15 предложений

.company_card
  .cover
  .item_card_info
    h3 Хлеб Насущный на какой-то улице
    .details
      p Здоровая еда
      span •
      p.orange 15 предложений

.company_card
  .cover
  .item_card_info
    h3 Хлеб Насущный
    .details
      p Здоровая еда
      span •
      p.orange 15 предложений

app/views/companies/_outlet_list.html.slim
= outlet.id
= display_full_address(outlet.address)

app/views/companies/index.html.slim
- @companies.each do |company|
  = company.company_name


= link_to 'Создать компанию',  new_company_path

app/views/companies/new.html.slim
h1 Ты можешь создать форму
p
= form_with(model: @company, local: true) do |form|
  - if @company.errors.any?
    #error_explanation
      h2
        = pluralize(@company.errors.count, "error")
        |  prohibited this outlet from being saved:
      ul
        - @company.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :company_name
    = form.text_field :company_name

  .field
    = form.label :company_category
    = select_tag :company_category, options_for_select(company_categories)


  h3 Создать нового пользователя:

  = form.fields_for :user, User.new do |user_attributes|
    = user_attributes.label :name, "email:"
    = user_attributes.email_field :email

    = user_attributes.label :password, "password:"
    = user_attributes.text_field :password

  .actions
    = form.submit

app/views/companies/show.html.slim
- if can? :manage, Company
  = render partial: 'outlet_list', collection: @outlets, as: :outlet

= current_user.id
= current_user.role
= current_user.company.company_name