config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'

  get 'pages/home_page'
  get 'users/outlet_list'
  devise_for :users
  resource :batches, only: %i[update create]
  resources :companies
  devise_for :outlets, path: 'auth', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
  # devise_scope :outlet do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  # end

  resources :outlets do
    resources :products
  end

end

app/models/batch.rb
# frozen_string_literal: true

class Batch < ApplicationRecord
  has_many :batches_products, dependent: :destroy
  has_many :products, through: :batches_products
  belongs_to :user
  belongs_to :outlet

  accepts_nested_attributes_for :batches_products

  enum discount: %w[25 50 75]

  scope :with_products, lambda {
    joins(:batches_products, :outlet)
    .select('batches.*, COUNT(batches_products.id) AS products_count')
    .where('batches_products.quantity > 0')
    .having('COUNT(batches_products.id) > 0')
    .includes(outlet: :company)
    .group(:id)
  }
end

app/controllers/batches_controller.rb
# frozen_string_literal: true

class BatchesController < ApplicationController
   

  def create
    @batch = current_user.batches.build(batch_params)
    @products = current_user.products

    respond_to do |format|
      if @batch.save
        format.html { redirect_to users_profile_path, notice: 'Updated' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render 'users/profile' }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

# TODO разобраться что делает этот метод и правильно ли он работает
  def update
    @batch = Batch.where('user_id = ? and DATE(activation_start) =?', current_user.id, Date.current.to_s).first
    @products = current_user.products

    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to users_profile_path, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render 'users/profile' }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def batch_params
    params.require(:batch).permit(:discount, :activation_start, :activation_end, batches_products_attributes: %i[product_id quantity id])
  end
end

app/helpers/batches_helper.rb
# frozen_string_literal: true

module BatchesHelper
end

app/views/batches/_batch.html.slim
table
  tbody
    - @batches.each do |batch|
      tr

      div
        = batch.activation_start.strftime("%H:%M %p")
        = batch.activation_end.strftime("%H:%M %p")
        = batch.discount
      td
        - #= link_to 'Show', batch
      td
        - #= link_to 'Edit', edit_batch_path(batch)
      td
        - #= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' }
br
- #= link_to 'New Batch', new_batch_path

app/views/batches/_form.html.slim
= form_with(model: batch, url: batches_path, local: true) do |form|
  - if batch.errors.any?
    #error_explanation
      h2
        = pluralize(batch.errors.count, "error")
        |  prohibited this batch from being saved:
      ul
        - batch.errors.full_messages.each do |message|
          li
            = message
  - products.map do |p|
    - unless form.object.batches_products.find_by(product_id: p.id)
      - form.object.batches_products << BatchesProduct.new(product: p)
  = form.fields_for :batches_products do |bp_field|
    = link_to 'New Product', new_product_path
    - product = bp_field.object.product
    = bp_field.hidden_field :product_id
    = bp_field.label product.name
    = product.category
    = number_to_human(product.weight_amount, units: {unit: "г", thousand: "кг"})
    = number_to_currency(product.price, unit: "₽", separator: ",", delimiter: "", format: "%n %u")
    = bp_field.number_field :quantity
    .product-pic
      - if product.product_pic.present?
        = image_tag product.product_pic.url
    - #= link_to 'Edit', edit_product_path(product)
    - #= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
  br
  .batch-panel
    div
      = form.label "Начало акции"
      = form.time_field :activation_start
    div
      = form.label "Конец акции"
      = form.time_field :activation_end
    div
      = form.label "Скидка на партию"
      = form.select :discount, Batch.discounts.keys
    p
      - if form.object.batches_products.exists?
        |  Позиций: 
        = form.object.batches_products.select{|bp| bp.quantity >= 1}.count
  .actions
    = form.submit

app/views/batches/edit.html.slim
h1
  | Editing Batch
= render 'form', batch: @batch
= link_to 'Show', @batch
|  | 
= link_to 'Back', batches_path

app/views/batches/index.html.slim
h1
  | Batches
table
  tbody
    - @batches.each do |batch|
      tr
        td
          = batch.discount
        td
          = batch.activation_start.strftime("%H:%M %p")
        td
          = batch.activation_end.strftime("%H:%M %p")
        td
          - #= link_to 'Show', batch
        td
          - #= link_to 'Edit', edit_batch_path(batch)
        td
          - #= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Batch', new_batch_path

app/views/batches/new.html.slim
h1
  | New Batch
= render 'form', batch: @batch
= link_to 'Back', batches_path

app/views/batches/show.html.slim
= render 'form', batch: @batch, products: @products