config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'

  get 'pages/home_page'
  get 'users/outlet_list'
  devise_for :users
  resource :batches, only: %i[update create]
  resources :companies
  devise_for :outlets, path: 'auth', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
  # devise_scope :outlet do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  # end

  resources :outlets do
    resources :products
  end

end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :batches_products, dependent: :destroy
  has_many :batches, through: :batches_products
  # belongs_to :user
  belongs_to :outlet

  # mount_uploader :product_pic, ProductPicUploader

  # data enumerizers
  enum weight_type: ['на вес', 'в порциях']
  enum category: ['Кулинария', 'Бакалея', 'Вегетарианское', 'Напитки', 'Сладкое']
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController

  # TO DO указать экшны в которых должен вызываться :get_outlet
  before_action :get_outlet
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @batch = @outlet.batches.where(
      'DATE(activation_start) = ? AND activation_end > ?' , Date.current.to_s, Time.current
    ).first
    @products = @outlet.products
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @product = @outlet.products.build
  end

  def edit; end

  def create
    @product = @outlet.products.build(product_params)
    # @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Продукт добавлен.' }
        # format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new, notice: 'Ошибка' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Product was successfully updated.' }
        # format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to outlet_products_path(@outlet), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = @outlet.products.find(params[:id])
  end

  def get_outlet
    @outlet = Outlet.find(params[:outlet_id])
  end

  def product_params
    params.require(:product).permit(
      :name,
      :price,
      :weight_type,
      :weight_amount,
      :product_pic,
      :category,
      :company_name,
      :outlet_id
    )
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def categories_collection
    Product.categories.collect do |k, v|
      k
    end
  end
end

app/views/products/_batch_product_card.html.slim
.batch_product_card
  .cover
    = image_tag product.product_pic.to_s

  .batch_product_card_info
    .details
      h4 #{product.name}
      h3 #{product.price} &#8381;
      h3 #{product.price-(product.price*discount/100)} &#8381;
      .quantity
        p.dark_grey Цена за #{product.weight_amount} #{product.weight_type}
        .button_quantity.button
          span -
          span 0
          span +
      .buttons
        = link_to 'Редактировать', edit_outlet_product_path(product.outlet, product),
          class: 'button_edit button'
        = link_to 'Удалить', outlet_product_path(product.outlet, product),
          method: :delete, data: { confirm: 'Вы уверены, что хотите удалить продукт?' },
            class: 'button_delete button'

app/views/products/_form.html.slim
= form_with(model: @product, url: outlet_products_path, html: {class: "product_form"}) do |form|
  .new_product
    = form.file_field :product_pic, class: 'file_field'
    .bread_form

  h2 #{form.text_field :name, placeholder: 'Введите название товара', size: 30, class: 'title_input'}

  hr.separator

  .measure
    = select_tag :category, options_for_select(categories_collection),
      class: 'button_category button', placeholder: 'Выберитe категорию'

    = form.radio_button :weight_type, 'в порциях'
    = form.label :weight_type, "в порциях", value: 'в порциях'

    = form.radio_button :weight_type, 'на вес', checked: true
    = form.label :weight_type, "на вес", value: 'на вес'

  .measure_inputs
    .measure_input
      p #{form.label :weight_amount, 'Вес порций'}
      = form.text_field :weight_amount, value: 0, class: 'input'

    .measure_input
      p #{ form.label :price, 'Цена без скидки' }
      = form.text_field :price, value: 0, class: 'input'

  .buttons
    = link_to 'Отмена', outlet_products_path(@outlet), class: 'button_edit button middle'
    = form.submit 'Сохранить', class: 'button_book button middle'

app/views/products/_index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Weight type</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Sale price</th>
      <th>Company name</th>
      <th>Batch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="product-pic"><%= image_tag product.product_pic.url %></td>
        <td><%= link_to product.name, product %></td>
        <td><%= product.category %></td>
        <td><%= number_to_human(product.weight_quantity, units: {unit: "г", thousand: "кг"}) %></td>
        <td><%#= product.weight_quantity %></td>
        <td><%= product.weight_type %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= product.sale_price %></td>
        <td><%= product.company_name %></td>
        <td><%= product.batch_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/_product_card.html.slim
= link_to 'Продукт', outlet_product_path(product.outlet, product), remote: true
.product_card
  .cover
    = image_tag(product.product_pic.to_s)
  .product_card_info
    .details
      h4 #{product.name}
      h3 #{product.price} &#8381;
      h3 #{product.price-(product.price*discount/100)} &#8381;
      p.dark_grey Цена за порцию / #{product.weight_amount} #{product.weight_type}

      .button_book.button Забронировать товар

app/views/products/_show.html.slim
.product_extended_card
  .cover
    = image_tag(product.product_pic.to_s)
  .product_card_info
    .details
      h4 #{product.name}
      h3 #{product.price} &#8381;
      p.dark_grey Цена за порцию / #{product.weight_amount} #{product.weight_type}

      .button_book.button Забронировать товар

app/views/products/edit.html.slim
.title
  .background
  h1  Редактировать #{@product.name}
  hr.separator

= render 'form', product: @product

app/views/products/index.html.slim
.title
  .background
  h1  Новая акция
  hr.separator

.products_container
  = link_to new_outlet_product_path do
    .new_product
      .add
      h3 Добавить продукт

  - @products.each do |product|
    = render partial: 'batch_product_card', locals: {product: product, discount: @batch.discount.to_i}

app/views/products/new.html.slim
.title
  .background
  h1  Новый продукт
  hr.separator

= render 'form', product: @product

app/views/products/show.js.slim
| console.log('I am working'); $modal = $('.modal'), $modalBody = $('.modal .modal-body'), $modalHeading = $('.modal .modal-heading'); console.log($modalHeading); $modalHeading.html("
= @product.name
| "); $modalBody.html("
= escape_javascript(render 'show', product: @product)
| "); $modal.modal(); 